[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[volumes]]
mountPath = "/app/h5p-storage"

[nixpacks]
pkgs = ["nodejs_22"]